version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${SERVER_PORT}:8080"
    env_file:
      - .env
    volumes:
      - ./test_logs_directory:/${LOG_DIR}
    restart: unless-stopped
    networks:
      my_network:
        ipv4_address: 10.5.0.2
  

networks:
  my_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/24
